# Generated by Django 3.1.1 on 2020-10-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
