# Generated by Django 3.1.1 on 2020-09-17 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanager.area')),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qgenerator', models.FileField(null=True, upload_to='Qgenerators/')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanager.area')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanager.topic')),
            ],
        ),
    ]
