# Generated by Django 3.1.1 on 2020-09-23 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanager', '0002_auto_20200918_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('totalQuestions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConceptInAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanager.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptInCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='conceptinchapter',
            name='chapterid',
        ),
        migrations.RemoveField(
            model_name='conceptinchapter',
            name='conceptid',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='area',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='ConceptInChapter',
        ),
        migrations.AddField(
            model_name='conceptincourse',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanager.concept'),
        ),
        migrations.AddField(
            model_name='conceptincourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanager.course'),
        ),
        migrations.AddField(
            model_name='conceptinassessment',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanager.concept'),
        ),
    ]
