# Generated by Django 3.1.1 on 2020-09-27 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanager', '0004_assessment_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptInSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanager.concept')),
            ],
        ),
        migrations.RenameModel(
            old_name='Assessment',
            new_name='Section',
        ),
        migrations.DeleteModel(
            name='ConceptInAssessment',
        ),
        migrations.AddField(
            model_name='conceptinsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanager.section'),
        ),
    ]
