# Generated by Django 3.1.1 on 2020-09-28 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanager', '0005_auto_20200928_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptInAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Section',
            new_name='Assessment',
        ),
        migrations.DeleteModel(
            name='ConceptInSection',
        ),
        migrations.AddField(
            model_name='conceptinassessment',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanager.assessment'),
        ),
        migrations.AddField(
            model_name='conceptinassessment',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanager.concept'),
        ),
    ]
