# Generated by Django 3.1.1 on 2020-09-28 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contentmanager', '0006_auto_20200928_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanager.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanager.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AsssessmentPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.IntegerField()),
                ('assessmentEnrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanager.assessmentenrollment')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanager.concept')),
            ],
            options={
                'ordering': ['-performance'],
            },
        ),
        migrations.AddField(
            model_name='assessmentenrollment',
            name='courseEnrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanager.courseenrollment'),
        ),
    ]
