# Generated by Django 3.1.1 on 2020-10-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanager', '0007_auto_20200928_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentenrollment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
