# Generated by Django 3.1.1 on 2020-11-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanager', '0008_assessmentenrollment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentenrollment',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
